# Generated by Django 4.1.3 on 2023-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d/'),
        ),
    ]
